### ISSUE TITLE
Flaky Tests

### ISSUE THREAD

**Issue by hutson** [xeb/sonar-coverage-badge#8]
The tests depend on a resource on a live server. Since the resource no longer exists, the pull requests are failing.
#7
#6

**Comment by xeb** [comment]
Looks like the example Nemo SonarQube server changed the PHP project I was testing with.  I really don't like having tests directly against a real sonar server.  Ideally, a full integration test against a server that Travis spins up would be nice.  But I'd still want local executions to function.  Will think about it more.

**Comment by xeb** [comment]
Commit 51c3dd6 should address the issue, but the flakiness remains.
